import React,{useState} from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter() 
  const [search, setSearch] = useState("");
  const handleChange = (e) => {
    setSearch(e.target.value);
  };
  function handleSubmit(e) {
    e.preventDefault()
    router.push({pathname:`/containdata`,query: {data:search}});
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <form action="" onSubmit={(e)=>handleSubmit(e)}>
        <input type="text" value ={search} onChange={(e) => handleChange(e)} />
        <button >
            submit
        </button>
      </form>
    </div>
    </>
  )
}
